version: 0.0.1
provider:
  name: huawei
  region: cn-north-4

vars:
  testv: testVarValue
  handler: index.handler

stages:
  default:
    node_env: default
  dev:
    region: ${vars.region}
    node_env: development
  prod:
    node_env: prod
service: insight-poc

tags:
  owner: geek-fun

functions:
  insight_poc_fn:
    name: insight-poc-fn
    code:
      runtime: nodejs18
      handler: ${vars.handler}
      path: tests/fixtures/artifacts/artifact.zip
    memory: 512
    timeout: 10
    environment:
      NODE_ENV: ${stages.node_env}
      TEST_VAR: ${vars.testv}
      TEST_VAR_EXTRA: abcds-${vars.testv}-andyou

#databases:
#  insight_es_db:
#    name: insight-poc-es
#    type: ELASTICSEARCH_SERVERLESS
#    version: 7.10
#    engine_mode: SEARCH
#    security:
#      basic_auth:
#        password: 123456
#    cu: 1
#    storage_size: 20

events:
  gateway_event:
    type: API_GATEWAY
    name: insight-poc-gateway
    triggers:
      - method: GET
        path: /api/hello
        backend: ${functions.insight_poc_fn}
#    custom_domain:
#      domain_name: test.com
#      certificate_name: test
#      certificate_private_key: test
#      certificate_body: test
