version: 0.0.1
provider:
  name: tencent
  region: ap-guangzhou

vars:
  testv: testVarValue
  handler: index.handler

stages:
  default:
    node_env: default
  dev:
    node_env: development
    memory: 512
  prod:
    node_env: production
    memory: 1024

service: insight-poc-scf

tags:
  owner: geek-fun

functions:
  insight_poc_fn:
    name: insight-poc-api-fn
    code:
      # Supported runtimes: nodejs20, nodejs18, nodejs16, nodejs14, nodejs12, nodejs10, nodejs8,
      # python3.10, python3.9, python3, PHP7.2, Java11, .NETCore3.1, Go1.x
      runtime: nodejs18
      handler: index.handler
      path: tests/fixtures/artifacts/artifact.zip
    memory: ${stages.memory}
    timeout: 10
    environment:
      NODE_ENV: ${stages.node_env}
      TEST_VAR: ${vars.testv}
