version: 0.0.1
provider:
  name: tencent
  region: ap-guangzhou

vars:
  testv: testVarValue
  handler: index.handler

stages:
  default:
    node_env: default
  dev:
    node_env: development
    memory: 512
  prod:
    node_env: production
    memory: 1024

service: insight-poc-scf

tags:
  owner: geek-fun

functions:
  insight_poc_fn:
    name: insight-poc-api-fn
    code:
      runtime: nodejs18
      handler: index.handler
      path: artifacts/scf_code.zip
    memory: ${stages.memory}
    timeout: 10
    environment:
      NODE_ENV: ${stages.node_env}
      TEST_VAR: ${vars.testv}
