FROM alpine:latest

RUN apk update && apk add --no-cache jq

# install aliyuncli
RUN wget https://aliyuncli.alicdn.com/aliyun-cli-linux-latest-amd64.tgz
RUN tar -xvzf aliyun-cli-linux-latest-amd64.tgz
RUN rm aliyun-cli-linux-latest-amd64.tgz
RUN mv aliyun /usr/local/bin/

# 注意：alpine需要额外创建 lib64 的动态链接库软连接
RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2
