import { DescribeClustersResponse } from 'tencentcloud-sdk-nodejs-cynosdb/tencentcloud/services/cynosdb/v20190107/cynosdb_models';
import { TdsqlcClusterInfo } from './types';

export type SdkCluster = NonNullable<DescribeClustersResponse['ClusterSet']>[number];

// Maps a raw DescribeClusters SDK record into the normalized TdsqlcClusterInfo
// shape shared by getCluster / getClusterByName probes.
export const mapClusterToInfo = (cluster: SdkCluster, region: string): TdsqlcClusterInfo => {
  return {
    ClusterId: cluster.ClusterId || '',
    ClusterName: cluster.ClusterName || '',
    Region: cluster.Region || region,
    Uin: cluster.Uin,
    AppId: cluster.AppId,
    Zone: cluster.Zone,
    PhysicalZone: cluster.PhysicalZone,
    DbType: cluster.DbType || '',
    DbVersion: cluster.DbVersion || '',
    DbMode: cluster.DbMode,
    Status: cluster.Status || '',
    StatusDesc: cluster.StatusDesc,
    ServerlessStatus: cluster.ServerlessStatus,
    VpcId: cluster.VpcId,
    VpcName: undefined,
    SubnetId: cluster.SubnetId,
    SubnetName: undefined,
    Charset: undefined,
    Vip: cluster.Vip,
    Vport: cluster.Vport,
    WanDomain: undefined,
    WanIP: undefined,
    WanPort: undefined,
    WanStatus: undefined,
    MinCpu: undefined,
    MaxCpu: undefined,
    MinStorageSize: cluster.MinStorageSize,
    MaxStorageSize: cluster.MaxStorageSize,
    StorageId: cluster.StorageId,
    Storage: cluster.Storage,
    StorageLimit: cluster.StorageLimit,
    StoragePayMode: cluster.StoragePayMode,
    // DescribeClusters returns ServerlessStatus as 'resume'/'pause' — that is
    // the cluster's running state, NOT the AutoPause idle-stall switch, so it
    // must not be mis-mapped here (AutoPause comes from the create/update config).
    AutoPause: undefined,
    AutoPauseDelay: undefined,
    CreateTime: cluster.CreateTime,
    UpdateTime: cluster.UpdateTime,
    ProjectId: cluster.ProjectID,
    PayMode: cluster.PayMode,
    PeriodEndTime: cluster.PeriodEndTime,
    AutoRenewFlag: cluster.RenewFlag,
    InstanceCount: cluster.InstanceNum,
    ProcessingTask: cluster.ProcessingTask,
    Tasks: cluster.Tasks,
    NetAddrs: cluster.NetAddrs,
    HasSlaveZone: cluster.HasSlaveZone,
    ResourcePackages: cluster.ResourcePackages,
    GdnId: cluster.GdnId,
    GdnRole: cluster.GdnRole,
    SupportedFeatures: undefined,
    RollbackSupport: undefined,
    NetworkType: undefined,
    ResourcePackageId: undefined,
    ResourcePackageType: undefined,
    ResourcePackageState: undefined,
    PhysicalRegion: undefined,
    ProxyStatus: undefined,
    RwGroupId: undefined,
    MasterZone: cluster.MasterZone,
    SlaveZones: cluster.SlaveZones,
    BusinessType: cluster.BusinessType,
    IsFreeze: cluster.IsFreeze,
    OrderSource: cluster.OrderSource,
    Ability: cluster.Ability,
    ResourceTags: cluster.ResourceTags,
    CynosVersion: cluster.CynosVersion,
    CynosVersionTag: cluster.CynosVersionTag,
    CynosVersionStatus: undefined,
    IsLatestVersion: undefined,
  };
};
